"""
Django settings for coded_nineteen project.

Generated by 'django-admin startproject' using Django 3.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

from . import sKeys
import os
from datetime import datetime

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = sKeys.SECRET_KEY

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = [u'coded-19.com', '167.99.83.36']


# Application definition

INSTALLED_APPS = [
    'blog.apps.BlogConfig',
    'users.apps.UsersConfig',
    'crispy_forms',
    'markdownx',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'storages',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'coded_nineteen.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'coded_nineteen.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': sKeys.DB_NAME,
        'USER': sKeys.DB_USER,
        'PASSWORD': sKeys.DB_PASSWORD,
        'HOST': 'localhost',
        'PORT': '',
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE   = 'en-us'

TIME_ZONE       = 'UTC'

USE_I18N        = True

USE_L10N        = True

USE_TZ          = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/
# STATIC_ROOT = os.path.join(BASE_DIR, "static/")

STATIC_ROOT = os.path.join(BASE_DIR, '/static/')
#STATIC_ROOT ='/var/www/staticfiles'
STATIC_URL = '/static/'
STATIC_DIR = os.path.join(BASE_DIR,'static')

STATICFILES_DIRS = [
    STATIC_DIR,
]

# USE_S3 = os.getenv('USE_S3') == 'TRUE'

# aws settings
# AWS_ACCESS_KEY_ID           = sKeys.AWS_ACCESS_KEY_ID
# AWS_SECRET_ACCESS_KEY       = sKeys.AWS_SECRET_ACCESS_KEY
# AWS_STORAGE_BUCKET_NAME     = sKeys.AWS_STORAGE_BUCKET_NAME
# AWS_DEFAULT_ACL             = None
# AWS_S3_CUSTOM_DOMAIN        = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'
# AWS_S3_OBJECT_PARAMETERS    = {'CacheControl': 'max-age=86400'}
# # s3 static settings
# AWS_LOCATION                = 'static'
# STATIC_URL                  = f'https://{AWS_S3_CUSTOM_DOMAIN}/{AWS_LOCATION}/'
# STATICFILES_STORAGE         = 'storages.backends.s3boto3.S3Boto3Storage'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')
MEDIA_URL = '/media/'

MARKDOWNX_MEDIA_PATH = datetime.now().strftime('markdownx/%Y/%m/%d')    # Image folders based on date of upload
MARKDOWNX_IMAGE_MAX_SIZE = {'size': (100, 100), 'quality': 90}          # Small pictures pls
MARKDOWNX_UPLOAD_MAX_SIZE = 2 * 1024 * 1024                             # 2MB in Bytes


CRISPY_TEMPLATE_PACK    = 'bootstrap4'

LOGIN_REDIRECT_URL      = 'blog-home'
LOGIN_URL               = 'login'

EMAIL_USE_TLS           = True
EMAIL_BACKEND           = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST              = 'smtp.gmail.com' 
EMAIL_HOST_USER         = 'kraboobee@gmail.com'
EMAIL_HOST_PASSWORD     = sKeys.GMAIL_PASSWORD
EMAIL_PORT              = 587
DEFAULT_FROM_EMAIL      = 'kraboobee@gmail.com'
SERVER_EMAIL            = 'kraboobee@gmail.com'

AWS_ACCESS_KEY_ID       = sKeys.AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY   = sKeys.AWS_SECRET_ACCESS_KEY
AWS_STORAGE_BUCKET_NAME = sKeys.AWS_STORAGE_BUCKET_NAME

AWS_S3_REGION_NAME      = 'eu-west-1' #change to your region
# AWS_S3_SIGNATURE_VERSION = 's3v4'

AWS_S3_FILE_OVERWRITE   = False
AWS_DEFAULT_ACL         = None
DEFAULT_FILE_STORAGE    = 'storages.backends.s3boto3.S3Boto3Storage'

# AWS_S3_CUSTOM_DOMAIN    = '%s.s3.amazonaws.com' % AWS_STORAGE_BUCKET_NAME
# STATICFILES_STORAGE     = 'storages.backends.s3boto3.S3Boto3Storage'
